### ISSUE TITLE
Incompatibility with dynamic dns hostnames (no-ip.org and ddns)

### ISSUE THREAD

**Issue by hugomza2003** [ticketz-oss/ticketz#67]
good day, install (curl -sSL get.ticke.tz | sudo bash -s backend.example.com frontend.example.com name@example.com) and I get a refresh token error, does anyone have the same problem.
The 2 subdomains are from noip.com pointing to my server with dns record A.
thank you

**Expected behavior**

**Screenshots**
refresh_token 401 (Unauthorized)

**Desktop (please complete the following information):**
 - OS: [ubuntu 22.04]
 - Browser [ chrome]

**Comment by hugomza2003** [comment]
The error occurs only with Google Chrome, with Firefox it works ok.

**Comment by allgood** [comment]
Looks like you are having a CORS issue. I wasn't able to simulate this fail here.

**Comment by allgood** [comment]
Google chrome has a built-in list with some services, including cloudfront.net, no-ip.org and many domains managed by dynamic dns services.

This is a security related behaviour, this avoids cross-site cookies between sites using the same service.

The list of the sites that causes this problem is available at https://publicsuffix.org/

**Comment by allgood** [comment]
This may be fixed when #91 gets fixed.
